name: Workflow with Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Test:
    runs-on: ubuntu
    steps:
    - run: echo "🧪 Testing..."
